apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-microservice-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-app
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
        - name: hello-app-container
          image: ghcr.io/jakubhomolka/hello-microservice:v1.0
          ports: 
            - containerPort: 5000
          